###Register User
post http://localhost:5300/user-api/register
Content-Type: application/json

{
    "username":"admin",
    "password":"admin",
    "mobileNo":123456789,
    "email":"admin@gmail.com"
}

### Login user
post http://localhost:5100/user-api/login
Content-Type: application/json

{
    "username":"ravi_04",
    "password":"ravi2004",
    "mobileNo":126564789
}

###Add a product to cart
put http://localhost:5100/user-api/add-to-cart/ravi_04/1716217773/2

### Increase cart item count
put http://localhost:5100/user-api/increase-cart-count/ravi_04/1716217773

### Decrease cart item count
put http://localhost:5100/user-api/decrease-cart-count/ravi_04/1716217773

###Add a product to wishlist
put http://localhost:5100/user-api/add-to-wishlist/ravi_04/1716217773

###Add a product to save for later
put http://localhost:5100/user-api/add-to-savelater/ravi_04/1716217773

###remove a product from cart
put http://localhost:5100/user-api/remove-cart/ravi_04/1716217773

###remove a product from wishlist
put http://localhost:5100/user-api/remove-wishlist/ravi_04/1716217773

###remove from save for later
put http://localhost:5100/user-api/remove-savelater/ravi_04/1716217773

###Display from cart
get http://localhost:5100/user-api/display-cart/ravi_04

###Display wishlist
get http://localhost:5100/user-api/display-wishlist/ravi_04

###Display save for later
get http://localhost:5100/user-api/display-savelater/ravi_04

###Get display of all the products
get http://localhost:5100/user-api/products

//------------------Admin Operations-------------------------
### Add a prooduct
post http://localhost:5100/admin-api/add-product
Content-Type: application/json

{
    "productid":"{{$timestamp}}",
    "title":"Watch",
    "description":"lorem ipsum...",
    "price":5200,
    "discountPercentage":5.6,
    "rating":4.6,
    "stock":15,
    "brand":"puma",
    "category":"fashion",
    "priceAfterDiscount":2633,
    "images":[],
    "display_status":true
}

###soft delete a product
put http://localhost:5100/admin-api/disable/1716051612

###enable a product
put http://localhost:5100/admin-api/enable/1716051612

###Get display of all the products
get http://localhost:5100/admin-api/products

###Change stock of product
put http://localhost:5100/admin-api/change-stock/1716051612/25

###Chnage discount price of a product
put http://localhost:5100/admin-api/change-discount/1716051612/10


###Modify a product
put http://localhost:5100/admin-api/modify-product
Content-Type: application/json

{
    "productid":"1716051612",
    "title":"Watch",
    "description":"lorem ipsum...",
    "price":6200,
    "discountPercentage":5.6,
    "rating":4.6,
    "stock":15,
    "brand":"puma",
    "category":"fashion",
    "priceAfterDiscount":2633,
    "images":[],
    "display_status":true
}

